// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/Cliente.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace EntryPoints.GRPC.Protos {
  /// <summary>
  /// Servicios
  /// </summary>
  public static partial class ServicioDeClientes
  {
    static readonly string __ServiceName = "clientes.ServicioDeClientes";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.GRPC.Protos.CrearClienteRequest> __Marshaller_clientes_CrearClienteRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.GRPC.Protos.CrearClienteRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.GRPC.Protos.StandardResponse> __Marshaller_clientes_StandardResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.GRPC.Protos.StandardResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.GRPC.Protos.SolicitarCreditoRequest> __Marshaller_clientes_SolicitarCreditoRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.GRPC.Protos.SolicitarCreditoRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.GRPC.Protos.PagarCuotaRequest> __Marshaller_clientes_PagarCuotaRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.GRPC.Protos.PagarCuotaRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.GRPC.Protos.DocumentoDeIdentidad> __Marshaller_clientes_DocumentoDeIdentidad = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.GRPC.Protos.DocumentoDeIdentidad.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.GRPC.Protos.CrearClienteRequest, global::EntryPoints.GRPC.Protos.StandardResponse> __Method_CrearCliente = new grpc::Method<global::EntryPoints.GRPC.Protos.CrearClienteRequest, global::EntryPoints.GRPC.Protos.StandardResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CrearCliente",
        __Marshaller_clientes_CrearClienteRequest,
        __Marshaller_clientes_StandardResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.GRPC.Protos.SolicitarCreditoRequest, global::EntryPoints.GRPC.Protos.StandardResponse> __Method_SolicitarCredito = new grpc::Method<global::EntryPoints.GRPC.Protos.SolicitarCreditoRequest, global::EntryPoints.GRPC.Protos.StandardResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SolicitarCredito",
        __Marshaller_clientes_SolicitarCreditoRequest,
        __Marshaller_clientes_StandardResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.GRPC.Protos.PagarCuotaRequest, global::EntryPoints.GRPC.Protos.StandardResponse> __Method_PagarCuota = new grpc::Method<global::EntryPoints.GRPC.Protos.PagarCuotaRequest, global::EntryPoints.GRPC.Protos.StandardResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PagarCuota",
        __Marshaller_clientes_PagarCuotaRequest,
        __Marshaller_clientes_StandardResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.GRPC.Protos.DocumentoDeIdentidad, global::EntryPoints.GRPC.Protos.StandardResponse> __Method_ObtenerClientePorDocumentoDeIdentidad = new grpc::Method<global::EntryPoints.GRPC.Protos.DocumentoDeIdentidad, global::EntryPoints.GRPC.Protos.StandardResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ObtenerClientePorDocumentoDeIdentidad",
        __Marshaller_clientes_DocumentoDeIdentidad,
        __Marshaller_clientes_StandardResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::EntryPoints.GRPC.Protos.ClienteReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ServicioDeClientes</summary>
    [grpc::BindServiceMethod(typeof(ServicioDeClientes), "BindService")]
    public abstract partial class ServicioDeClientesBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.GRPC.Protos.StandardResponse> CrearCliente(global::EntryPoints.GRPC.Protos.CrearClienteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.GRPC.Protos.StandardResponse> SolicitarCredito(global::EntryPoints.GRPC.Protos.SolicitarCreditoRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.GRPC.Protos.StandardResponse> PagarCuota(global::EntryPoints.GRPC.Protos.PagarCuotaRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.GRPC.Protos.StandardResponse> ObtenerClientePorDocumentoDeIdentidad(global::EntryPoints.GRPC.Protos.DocumentoDeIdentidad request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ServicioDeClientes</summary>
    public partial class ServicioDeClientesClient : grpc::ClientBase<ServicioDeClientesClient>
    {
      /// <summary>Creates a new client for ServicioDeClientes</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ServicioDeClientesClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ServicioDeClientes that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ServicioDeClientesClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ServicioDeClientesClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ServicioDeClientesClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.GRPC.Protos.StandardResponse CrearCliente(global::EntryPoints.GRPC.Protos.CrearClienteRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CrearCliente(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.GRPC.Protos.StandardResponse CrearCliente(global::EntryPoints.GRPC.Protos.CrearClienteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CrearCliente, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.GRPC.Protos.StandardResponse> CrearClienteAsync(global::EntryPoints.GRPC.Protos.CrearClienteRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CrearClienteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.GRPC.Protos.StandardResponse> CrearClienteAsync(global::EntryPoints.GRPC.Protos.CrearClienteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CrearCliente, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.GRPC.Protos.StandardResponse SolicitarCredito(global::EntryPoints.GRPC.Protos.SolicitarCreditoRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SolicitarCredito(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.GRPC.Protos.StandardResponse SolicitarCredito(global::EntryPoints.GRPC.Protos.SolicitarCreditoRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SolicitarCredito, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.GRPC.Protos.StandardResponse> SolicitarCreditoAsync(global::EntryPoints.GRPC.Protos.SolicitarCreditoRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SolicitarCreditoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.GRPC.Protos.StandardResponse> SolicitarCreditoAsync(global::EntryPoints.GRPC.Protos.SolicitarCreditoRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SolicitarCredito, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.GRPC.Protos.StandardResponse PagarCuota(global::EntryPoints.GRPC.Protos.PagarCuotaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PagarCuota(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.GRPC.Protos.StandardResponse PagarCuota(global::EntryPoints.GRPC.Protos.PagarCuotaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PagarCuota, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.GRPC.Protos.StandardResponse> PagarCuotaAsync(global::EntryPoints.GRPC.Protos.PagarCuotaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PagarCuotaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.GRPC.Protos.StandardResponse> PagarCuotaAsync(global::EntryPoints.GRPC.Protos.PagarCuotaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PagarCuota, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.GRPC.Protos.StandardResponse ObtenerClientePorDocumentoDeIdentidad(global::EntryPoints.GRPC.Protos.DocumentoDeIdentidad request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ObtenerClientePorDocumentoDeIdentidad(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.GRPC.Protos.StandardResponse ObtenerClientePorDocumentoDeIdentidad(global::EntryPoints.GRPC.Protos.DocumentoDeIdentidad request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ObtenerClientePorDocumentoDeIdentidad, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.GRPC.Protos.StandardResponse> ObtenerClientePorDocumentoDeIdentidadAsync(global::EntryPoints.GRPC.Protos.DocumentoDeIdentidad request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ObtenerClientePorDocumentoDeIdentidadAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.GRPC.Protos.StandardResponse> ObtenerClientePorDocumentoDeIdentidadAsync(global::EntryPoints.GRPC.Protos.DocumentoDeIdentidad request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ObtenerClientePorDocumentoDeIdentidad, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ServicioDeClientesClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ServicioDeClientesClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ServicioDeClientesBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CrearCliente, serviceImpl.CrearCliente)
          .AddMethod(__Method_SolicitarCredito, serviceImpl.SolicitarCredito)
          .AddMethod(__Method_PagarCuota, serviceImpl.PagarCuota)
          .AddMethod(__Method_ObtenerClientePorDocumentoDeIdentidad, serviceImpl.ObtenerClientePorDocumentoDeIdentidad).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ServicioDeClientesBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CrearCliente, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.GRPC.Protos.CrearClienteRequest, global::EntryPoints.GRPC.Protos.StandardResponse>(serviceImpl.CrearCliente));
      serviceBinder.AddMethod(__Method_SolicitarCredito, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.GRPC.Protos.SolicitarCreditoRequest, global::EntryPoints.GRPC.Protos.StandardResponse>(serviceImpl.SolicitarCredito));
      serviceBinder.AddMethod(__Method_PagarCuota, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.GRPC.Protos.PagarCuotaRequest, global::EntryPoints.GRPC.Protos.StandardResponse>(serviceImpl.PagarCuota));
      serviceBinder.AddMethod(__Method_ObtenerClientePorDocumentoDeIdentidad, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.GRPC.Protos.DocumentoDeIdentidad, global::EntryPoints.GRPC.Protos.StandardResponse>(serviceImpl.ObtenerClientePorDocumentoDeIdentidad));
    }

  }
}
#endregion
